### PR TITLE
Creation of system chips for players and NPCs

### PR DESCRIPTION
**Pull request by luizrpgluiz**
I would like to ask for an increase of a request or novelty for the future version of the program, which would be the creation of semi automatic bookmarks for players with modifying values as the semi automatic bookmarks for the D&D

### CODE REVIEW

**Comment by obiwankennedy** [comment]
Hi, 

I don't know why you submit your question as 'pull request'.
If you want to ask for new features, you can do it into the bug/feature system: https://github.com/Rolisteam/rolisteam/issues/new. 

I invite you to do it and add as much details as you can. What do you mean by semi-automatic bookmark ? 
Do you have an example ?

**Comment by luizrpgluiz** [comment]
for example, in the RRPG Firecast program, has the player form creation system as a character name, race, its modifiers dexterity, strength, life points of the character, etc.

**Comment by obiwankennedy** [comment]
If you means a charactersheet system. It is planned for the next release.
With many other things.

**Comment by obiwankennedy** [comment]
I close this because it is not a proper pull request. 
The feature is a work in progess.

**Pull request closed without merging**
